# Generated by Django 5.2.17 on 2026-09-25 12:15

import api.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('surface', models.CharField(choices=[('floor', 'Floor'), ('ceiling', 'Ceiling'), ('wall_front', 'Wall Front'), ('wall_back', 'Wall Back'), ('wall_left', 'Wall Left'), ('wall_right', 'Wall Right'), ('partition_a', 'Custom Wall Side A'), ('partition_b', 'Custom Wall Side B')], max_length=20)),
                ('image', models.ImageField(upload_to=api.models.texture_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
