# Generated by Django 5.2.17 on 2026-09-25 13:43

import api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('furniture', 'Furniture'), ('ceiling', 'Ceiling'), ('wall', 'Wall'), ('windows', 'Windows'), ('doors', 'Doors'), ('floor', 'Floor'), ('decor', 'Decor')], max_length=20)),
                ('shape', models.CharField(blank=True, default='', help_text='Procedural builder key (sofa, fridge, niche_wall...). Leave empty if using a GLB file.', max_length=40)),
                ('model_file', models.FileField(blank=True, help_text='Draco-compressed .glb file', null=True, upload_to=api.models.asset_model_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=api.models.asset_thumb_path)),
                ('surface', models.CharField(choices=[('floor', 'Floor'), ('ceiling', 'Ceiling'), ('wall', 'Wall')], default='floor', max_length=10)),
                ('default_width', models.FloatField(default=1.0)),
                ('default_height', models.FloatField(default=1.0)),
                ('default_depth', models.FloatField(default=1.0)),
                ('color', models.CharField(blank=True, default='#4f7ec0', max_length=9)),
                ('accent_color', models.CharField(blank=True, default='#e8e2d6', max_length=9)),
                ('emit_light', models.BooleanField(default=False)),
                ('cut_opening', models.BooleanField(default=False)),
                ('is_partition', models.BooleanField(default=False)),
                ('partition_style', models.CharField(blank=True, default='', max_length=20)),
                ('default_v', models.FloatField(blank=True, null=True)),
                ('default_sill', models.FloatField(blank=True, null=True)),
                ('license', models.CharField(blank=True, default='CC0', max_length=60)),
                ('source_url', models.URLField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
